spring:
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: ${OIDC_CLIENT_ID:rp-simulator}
            client-secret: ${OIDC_CLIENT_SECRET:changeme}
            scope: ${OIDC_SCOPES:openid,profile,email}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          oidc-client:
            issuer-uri: ${OIDC_ISSUER_URI:https://example.com}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8080
