spring:
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: ${OIDC_CLIENT_ID}
            client-secret: ${OIDC_CLIENT_SECRET}
            scope: ${OIDC_SCOPES:openid,profile,email}
            authorization-grant-type: authorization_code
            redirect-uri: "${APP_BASE_URL}/callback"
        provider:
          oidc-client:
            issuer-uri: ${OIDC_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8080
